repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.93.0
    hooks:
      - id: terraform_fmt
      - id: terraform_validate
      # - id: terraform_tflint
      #   args:
      #     - --minimum-failure-severity=error


  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-merge-conflict
