apiVersion: v1
kind: ServiceAccount
metadata:
  name: app-sa
  namespace: dev
  annotations:
    # Optional: useful when using Workload Identity
    # azure.workload.identity/client-id: "<client-id-here>"
