{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "golden-app.fullname" . }}
  labels:
    {{- include "golden-app.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.ingress.className }}
  ingressClassName: {{ . | quote }}
  {{- end }}

  {{- if and (hasKey .Values.ingress "tls") (gt (len .Values.ingress.tls) 0) }}
  tls:
    {{- toYaml .Values.ingress.tls | nindent 4 }}
  {{- end }}

  rules:
    {{- if and (hasKey .Values.ingress "hosts") (gt (len .Values.ingress.hosts) 0) }}
    {{- range .Values.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- if and (hasKey . "paths") (gt (len .paths) 0) }}
          {{- range .paths }}
          - path: {{ .path | default "/" | quote }}
            pathType: {{ .pathType | default "Prefix" }}
            backend:
              service:
                name: {{ include "golden-app.fullname" $ }}
                port:
                  name: http
          {{- end }}
          {{- else }}
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: {{ include "golden-app.fullname" $ }}
                port:
                  name: http
          {{- end }}
    {{- end }}
    {{- else }}
    - host: "app.local"
      http:
        paths:
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: {{ include "golden-app.fullname" . }}
                port:
                  name: http
    {{- end }}
{{- end -}}
