{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "golden-app.serviceAccountName" . }}
  labels:
{{ include "golden-app.labels" . | nindent 4 }}
  {{- if .Values.workloadIdentity.enabled }}
  annotations:
    azure.workload.identity/client-id: {{ required "workloadIdentity.clientId is required when workloadIdentity.enabled=true" .Values.workloadIdentity.clientId | quote }}
  {{- end }}
{{- end }}
