observability:
  enabled: true
  env: test
  serviceName: golden-app
  appInsights:
    secretName: appinsights-connstr
    connectionStringKey: APPLICATIONINSIGHTS_CONNECTION_STRING
workloadIdentity:
  enabled: false
